spring:
  application:
    name: gestioncontact
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:gestioncontactdb
    driver-class-name: org.h2.Driver
    username: test
    password: password
  h2:
    console:
      enabled: true

server:
  port: 8080

springdoc:
  packages-to-scan: "com.genesis.gestioncontact.controller"
  paths-to-match: "/api/**"